<?php

/**
 * @file 
 * This Connects a Drupal webform to an ImageNow system
 * @author Stephen Corcoran
 */

/**
 * Implementation of the hook_menu()
 */
function uwpimagenow_menu() {
  $items = [];
  $items['admin/config/uwplatteville/imagenow'] = array(
    'title' => 'UW-Platteville ImageNow',
    'description' => 'Connect Drupal webforms to the ImageNow system. Tom Click Here!!!',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uwpimagenow_admin_settings'),
    'access arguments' => array('administer uwpimagenow'),
    'file' => 'uwpimagenow.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/uwplatteville/imagenow/portal'] = array(
    'title' => 'UW-Platteville ImageNow Portal',
    'description' => 'Portal Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uwpimagenow_portal_admin'),
    'access arguments' => array('administer uwpimagenow'),
    'file' => 'uwpimagenow_portal.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of the hook_theme()
 */
//function uwpimagenow_theme() {
//  return array(
//    'uwpimagenow_admin' => array(
//      'path' => drupal_get_path('module', 'uwpimagenow') . '/theme',
//      'template' => 'uwpimagenow-admin',
//      'arguments' => array('form' => NULL),
//      'render element' => 'form',
//    ),
//  );
//}

/**
 * Implementation of hook_permission
 */
function uwpimagenow_permission() {
  return array(
    'administer uwpimagenow' => array(
      'title' => t('Administer ImageNow Portal Control'),
      'description' => t('Access to ImageNow configuration'),
    ),
  );
}

/**
 * Implementation of hook_form_submit.
 * 
 * Take the ImageNow forms that pass validation
 * and submit them to imagenow system.
 * 
 * @param type $form_id
 * @param type $form_state
 */
function uwpimagenow_form_submit($form_id, $form_state){
  dsm("Test uwpimagenow");
  dsm($form_state);
  watchdog("CMO-php", 'Test uwpimagenow');
}

/**
 * Implements hook_form_alter().
 */
function uwpimagenow_form_alter(&$form_id, $form_state) {

  // Use this to reveal the form id.
  dsm($form_state);
  dsm($form_id);
  dsm($form_id['details']['nid']['#value']);
  // Use this with the devel module to inspect the button action(s).
  //kint($form['actions']);
  $tmp = _is_imagenow_form($form_id['details']['nid']['#value']);
  if($tmp){
    dsm("Is an ImageNow Form");
    $form['#validate'][] = 'uwpimagenow_form_submit';
    dsm($form['#validate']);
    //$form_id['actions']['publish']['#submit'][] = 'uwpimagenow_form_alter';
  }
}

function _is_imagenow_form($nid){
  $dbNids = NULL;
  // Get the portals from the Database
  $result = db_select('uwpimagenow_portals', 'portals')
    ->fields('portals', array('drupal_nid'))
    ->orderBy('inid', 'ASC')
    ->execute();
  // Organize portal elements
  foreach ($result as $row) {
    $dbNids[] = $row->drupal_nid;
  }
  dsm($dbNids);
  for($i = 0; $i < count($dbNids); $i++){
    if($nid == $dbNids[$i]){
      return TRUE;
    }
  }
  return FALSE;
}