<?php

/**
 * @file 
 * This Connects a Drupal webform to an ImageNow system
 * @author Stephen Corcoran
 */

/**
 * Implementation of the hook_menu()
 */
function uwpimagenow_menu() {
  $items = [];
  $items['admin/config/uwplatteville/imagenow'] = array(
    'title' => 'UW-Platteville ImageNow',
    'description' => 'Connect Drupal webforms to the ImageNow system. Tom Click Here!!!',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uwpimagenow_admin_settings'),
    'access arguments' => array('administer uwpimagenow'),
    'file' => 'uwpimagenow.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/uwplatteville/imagenow/portal'] = array(
    'title' => 'UW-Platteville ImageNow Portal',
    'description' => 'Portal Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uwpimagenow_portal_admin'),
    'access arguments' => array('administer uwpimagenow'),
    'file' => 'uwpimagenow_portal.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_permission
 */
function uwpimagenow_permission() {
  return array(
    'administer uwpimagenow' => array(
      'title' => t('Administer ImageNow Portal Control'),
      'description' => t('Access to ImageNow configuration'),
    ),
  );
}

function _submit_to_imagenow(&$form_values) {
//  $portal = _get_portal_config($form_values['details']['nid']);
//  dpm($portal);
//  //create array of data to be posted
//  $post_data = NULL;
//  for($i = 0; $i < count($portal['connections']); $i++){
//    $post_data[$portal['connections']['iek']] = $form_values['submitted'][$portal['connections']['dek']];
//  }
//
////traverse array and prepare data for posting (key1=value1)
//  foreach ($post_data as $key => $value) {
//    $post_items[] = $key . '=' . $value;
//  }
//  watchdog("CMO-PHP", $post_items);
////create the final string to be posted using implode()
//  $post_string = implode('&', $post_items);
//
////we also need to add a question mark at the beginning of the string
//  $post_string = '?' . $post_string;
//  watchdog("CMO-PHP", $post_string);
////we are going to need the length of the data string
//  $data_length = strlen($post_string);
//
////let's open the connection
//  $connection = fsockopen($portal['imagenow_url'], 80);
//
////sending the data
//  fputs($connection, "POST  /target_url.php  HTTP/1.1\r\n");
//  fputs($connection, "Host:  " . $portal['imagenow_url'] ." \r\n");
//  fputs($connection, "Content-Type: application/x-www-form-urlencoded\r\n");
//  fputs($connection, "Content-Length: $data_length\r\n");
//  fputs($connection, "Connection: close\r\n\r\n");
//  fputs($connection, $post_string);
//
////closing the connection
//  fclose($connection);
}

/**
 * Implementation of hook_form_submit.
 * 
 * Take the ImageNow forms that pass validation
 * and submit them to imagenow system.
 * 
 * @param type $form_id
 * @param type $form_state
 */
function uwpimagenow_form_validate($form, &$form_state) {
  if (form_get_errors()) return;
  //dpm("Test uwpimagenow");
  //dpm($form_state);
  //$index = $form_state['values']['details']['nid'];
  _submit_to_imagenow($form_state['values']);
  watchdog("CMO-php", 'Test uwpimagenow');
}

function _is_imagenow_form($nid) {
  $dbNids = NULL;
  // Get the portals from the Database
  $result = db_select('uwpimagenow_portals', 'portals')
    ->fields('portals', array('drupal_nid'))
    ->orderBy('inid', 'ASC')
    ->execute();
  // Organize portal elements
  foreach ($result as $row) {
    $dbNids[] = $row->drupal_nid;
  }
  for ($i = 0; $i < count($dbNids); $i++) {
    if ($nid == $dbNids[$i]) {
      return $dbNids[$i];
    }
  }
  return NULL;
}

/**
 * Implements hook_form_alter().
 */
function uwpimagenow_form_alter(&$form, &$form_state, $form_id) {
  $index = $form['details']['nid']['#value'];
  $tmp = _is_imagenow_form($index);
  if ($tmp != NULL) {
    $form['#validate'][] = 'uwpimagenow_form_validate';
  }
}
